// 這是你的專屬單字資料庫 (words.js)
// 格式：["英文單字", "中文", "英文例句1|英文例句2", "中文例句1|中文例句2"],

const COMPRESSED_DB = [
    ["office relocation", "辦公室搬遷", "The office relocation will be completed by next Monday.|We need to pack our desks before the office relocation.", "辦公室搬遷將在下週一前完成。|我們需要在辦公室搬遷前打包好桌面。"],
    ["reception desk", "接待台", "Please leave the room keys at the reception desk.|Our group of seven gathered at the reception desk.", "請將房間鑰匙留在接待台。|我們七個人在接待台集合。"],
    ["leading supplier", "主要供應商", "They are the leading supplier of sports equipment.|We signed a contract with the leading supplier.", "他們是運動設備的主要供應商。|我們與該主要供應商簽訂了合約。"],
    ["intended listener", "目標聽眾", "Make sure your speech reaches the intended listener.|The advertisement didn't attract its intended listener.", "確保你的演講能傳達給目標聽眾。|這則廣告並沒有吸引到它的目標聽眾。"],
    ["consultation", "諮詢", "I scheduled a quick consultation with the doctor.|The interior designer offers a free consultation.", "我安排了與醫生的快速諮詢。|這位室內設計師提供免費諮詢。"],
    ["upon", "一...就... / 在...之上", "Upon arrival at the airport, we will rent a car.|They agreed upon the budget for the trip.", "一抵達機場，我們就會去租車。|他們就這趟旅行的預算達成了共識。"],
    ["pottery", "陶器", "We bought some beautiful handmade pottery as souvenirs.|He is taking a pottery class on weekends.", "我們買了一些美麗的手工陶器當紀念品。|他週末在上有陶藝課。"],
    ["assess", "評估", "We need to assess the cost of the 10-day trip.|The coach will assess the players' fitness levels.", "我們需要評估這趟 10 天旅行的花費。|教練將評估球員們的體能狀況。"],
    ["vitality", "活力", "Working out weekly helps me maintain my vitality.|The fresh mountain air filled us with vitality.", "每週健身有助於我保持活力。|清新的高山空氣讓我們充滿了活力。"],
    ["command", "命令 / 指揮", "The dog immediately obeyed his command.|She has a good command of the English language.", "那隻狗立刻服從了他的命令。|她精通英語。"],
    ["fixtures", "固定裝置", "We are choosing new lighting fixtures for the living room.|The bathroom fixtures were recently updated.", "我們正在為客廳挑選新的照明燈具。|浴室的固定設備最近剛更新過。"],
    ["naturally", "自然地 / 當然", "Try to speak naturally when ordering food.|Naturally, we will split the bill seven ways.", "點餐時盡量自然地說話。|當然，我們會把帳單分成七份。"],
    ["obligation", "義務 / 責任", "You have no obligation to buy anything in that store.|It is our obligation to clean up before leaving.", "你在那家店裡沒有義務購買任何東西。|離開前清理乾淨是我們的責任。"],
    ["I cannot recommend the store enough", "我極力推薦這家店", "The service was perfect; I cannot recommend the store enough.|If you want a great burger, I cannot recommend the store enough.", "服務太完美了；我極力推薦這家店。|如果你想吃超讚的漢堡，我極力推薦這家店。"],
    ["verge", "邊緣", "I was on the verge of canceling the trip.|The company is on the verge of a major breakthrough.", "我差點就要取消這趟旅行了。|這家公司正處於重大突破的邊緣。"],
    ["a couple of other places", "其他幾個地方", "We plan to visit a couple of other places in New York.|Let's check a couple of other places before deciding.", "我們打算去紐約的其他幾個地方看看。|在決定之前，我們再去其他幾個地方看看吧。"],
    ["lost cause", "注定失敗的事", "Trying to change his mind is a lost cause.|Don't waste energy on a lost cause.", "試圖改變他的想法是白費力氣。|別把精力浪費在注定失敗的事情上。"],
    ["cause", "原因 / 引起", "What was the root cause of the delay?|The bad weather caused our flight to be canceled.", "延誤的根本原因是什麼？|惡劣的天氣導致我們的航班被取消。"],
    ["deal", "交易 / 處理", "We got a great deal on our hotel rooms.|Let me deal with this problem.", "我們的飯店房間拿到了很棒的折扣。|讓我來處理這個問題。"],
    ["disagreed", "不同意", "They strongly disagreed on where to eat tonight.|I disagreed with his proposed itinerary.", "他們對於今晚去哪吃飯意見非常不合。|我不同意他提議的行程。"],
    ["diagnose", "診斷", "The doctor was unable to diagnose his illness.|It is hard to diagnose the problem with the car.", "醫生無法診斷出他的病情。|很難診斷出這輛車的問題出在哪。"],
    ["swiftly", "迅速地", "The waitress moved swiftly to bring our drinks.|We need to act swiftly to catch the train.", "女服務生迅速地把我們的飲料送來。|我們需要迅速行動才趕得上火車。"],
    ["generally", "通常 / 大致上", "Americans generally leave a 15 to 20 percent tip.|I generally wake up at 7 AM.", "美國人通常會留 15% 到 20% 的小費。|我通常早上七點起床。"],
    ["enhancing", "增強 / 提升", "We are looking for ways of enhancing the customer experience.|Reading news is great for enhancing your English.", "我們正在尋找提升顧客體驗的方法。|閱讀新聞對增強你的英文很有幫助。"],
    ["acceptable", "可接受的", "Is this casual outfit acceptable for the restaurant?|The proposed budget is completely acceptable.", "這套休閒服裝去那家餐廳可以接受嗎？|提出來的預算完全可以接受。"],
    ["financial means", "財力", "They lack the financial means to support the project.|Do we have the financial means for a longer trip?", "他們缺乏財力來支持這個專案。|我們有足夠的財力延長旅程嗎？"],
    ["afford", "負擔得起", "We can't afford to miss this flight.|If we split the cost, everyone can afford it.", "我們承擔不起錯過這班飛機的後果。|如果我們平攤費用，每個人都負擔得起。"],
    ["appropriate", "適當的", "Please wear appropriate clothing for the hike.|Is this an appropriate time to call?", "請穿著適當的服裝去健行。|現在打電話是適當的時機嗎？"],
    ["disability", "殘疾", "The museum is fully accessible for people with a disability.|He overcame his physical disability to win the race.", "這間博物館對殘疾人士來說完全無障礙。|他克服了身體的殘障贏得了比賽。"],
    ["senior", "年長的 / 資深的", "Senior citizens get a discount at this cinema.|He is a senior engineer at the tech company.", "年長者在這家電影院可享折扣。|他是那家科技公司的資深工程師。"],
    ["citizen", "公民", "Are you a U.S. citizen?|Every citizen has the right to vote.", "你是美國公民嗎？|每個公民都有投票權。"],
    ["mobility", "機動性", "Regular exercise helps maintain joint mobility.|The new smartphone offers greater mobility for work.", "規律運動有助於維持關節活動力。|新的智慧型手機為工作提供了更大的機動性。"],
    ["caution", "警告 / 謹慎", "Proceed with caution when driving in the snow.|The sign advised caution due to the wet floor.", "在雪地開車請謹慎前行。|告示牌警告因為地板濕滑要小心。"],
    ["consumer", "消費者", "The company aims to protect consumer rights.|Consumer demand for eco-friendly products is rising.", "公司致力於保護消費者權益。|消費者對環保產品的需求正在上升。"],
    ["element", "要素 / 元素", "Trust is a key element in any relationship.|We need to consider the element of surprise.", "信任是任何關係中的關鍵要素。|我們需要把驚喜這個元素考慮進去。"],
    ["placement", "放置 / 佈置", "The product placement in the movie was very obvious.|We discussed the placement of the new sofa.", "這部電影裡的產品置入非常明顯。|我們討論了新沙發的擺放位置。"],
    ["assurance", "保證", "He gave me his assurance that the car would be ready.|I need some assurance before I sign the contract.", "他向我保證車子會準備好。|在簽約之前我需要一些保證。"],
    ["knit belt", "針織腰帶", "She bought a colorful knit belt to match her dress.|A knit belt is comfortable for a long flight.", "她買了一條色彩繽紛的針織腰帶搭配洋裝。|搭長途飛機時繫針織腰帶很舒服。"],
    ["even so", "即使如此", "It's raining heavily; even so, we will go out.|The trip was exhausting. Even so, I had a great time.", "雨下得很大；即使如此，我們還是要出門。|這趟旅行很累人。即使如此，我還是玩得很開心。"],
    ["despite", "儘管", "We arrived on time despite the heavy traffic.|He smiled despite the pain.", "儘管交通擁擠，我們還是準時抵達了。|儘管很痛，他還是笑了。"],
    ["tablet", "平板電腦 / 藥片", "I downloaded some movies onto my tablet for the flight.|Take one tablet twice a day after meals.", "我下載了一些電影到平板電腦裡準備在飛機上看。|這個藥片每天兩次，飯後服用。"],
    ["plant", "植物 / 工廠", "Don't forget to water the plant while I am away.|The car manufacturing plant employs thousands of people.", "我不在的時候別忘了幫植物澆水。|這家汽車製造廠雇用了數千名員工。"],
    ["leakage", "洩漏", "The plumber fixed the water leakage in the bathroom.|There was a sudden gas leakage in the building.", "水管工修好了浴室的漏水。|大樓裡突然發生了瓦斯外洩。"],
    ["combustion", "燃燒", "The engine works by internal combustion.|Combustion produces heat and light.", "引擎是靠內燃運作的。|燃燒會產生熱和光。"],
    ["reaction", "反應", "What was his reaction when you told him the news?|I had a bad allergic reaction to the seafood.", "當你告訴他這個消息時，他有什麼反應？|我對這海鮮產生了嚴重的過敏反應。"],
    ["stripping", "剝離", "They are stripping the old paint off the walls.|Stripping the cables requires a special tool.", "他們正在把牆上的舊油漆剝離掉。|剝開電纜外皮需要特殊工具。"],
    ["etching", "蝕刻", "The artist is famous for his glass etching.|The serial number is made by laser etching.", "這位藝術家以他的玻璃蝕刻聞名。|序號是透過雷射蝕刻製作的。"],
    ["factor", "因素", "Price was a major factor in our decision.|We must consider the weather factor before going out.", "價格是我們決定的一大因素。|出門前我們必須考慮天氣因素。"],
    ["stable", "穩定的", "The patient's condition is now stable.|I need a stable internet connection for my work.", "病人的情況現在穩定了。|我工作需要穩定的網路連線。"],
    ["dosing", "定量 / 劑量分配", "Proper dosing of the medicine is very important.|The machine handles the dosing of the chemicals.", "正確分配藥物劑量非常重要。|這台機器負責化學物質的定量分配。"],
    ["externally", "外部地", "This medicine should only be used externally.|The building was externally damaged by the storm.", "此藥物僅供外用。|這棟建築物外部受到了風暴的破壞。"],
    ["prevent", "預防 / 阻止", "Exercise can help prevent heart disease.|The security guard tried to prevent him from entering.", "運動有助於預防心臟病。|警衛試圖阻止他進入。"],
    ["scaling", "縮放 / 結垢", "The pipes were blocked due to heavy scaling.|Scaling the business will require more capital.", "水管因為嚴重的結垢而堵塞了。|擴張業務將需要更多資金。"],
    ["corrosion", "腐蝕", "The sea air causes rapid corrosion of the metal.|This paint protects the car against corrosion.", "海風會導致金屬迅速腐蝕。|這款油漆可以保護汽車免受腐蝕。"],
    ["growth", "增長 / 發展", "The company has seen rapid growth this year.|Personal growth is just as important as your career.", "公司今年的業績增長非常迅速。|個人成長和你的事業一樣重要。"],
    ["consolidate", "鞏固 / 合併", "Let's consolidate our luggage into one big suitcase.|The two banks decided to consolidate.", "我們把行李合併到一個大行李箱裡吧。|這兩家銀行決定合併。"],
    ["nightstand", "床頭櫃", "I left my phone on the nightstand.|There is a small lamp on the nightstand.", "我把手機留在床頭櫃上了。|床頭櫃上有一盞小燈。"],
    ["mounted", "安裝的 / 固定的", "The TV is securely mounted on the wall.|He easily mounted the horse.", "電視牢固地安裝在牆上。|他輕鬆地跨上了馬。"],
    ["within", "在...之內", "The hotel is within walking distance of the beach.|Please reply within three business days.", "這間飯店在步行即可抵達海灘的距離之內。|請在三個工作天內回覆。"],
    ["reserve", "保留 / 預訂", "I would like to reserve a table for seven people.|We need to reserve our energy for tomorrow's hike.", "我想要預訂一桌七個人的位子。|我們需要為明天的健行保留體力。"],
    ["tense", "緊張的", "The atmosphere in the meeting room was very tense.|Don't be so tense; just relax and enjoy the trip.", "會議室裡的氣氛非常緊張。|別這麼緊張；放輕鬆享受這趟旅行吧。"],
    ["hesitant", "猶豫的", "She was hesitant to try the spicy food.|Don't be hesitant to ask the locals for directions.", "她對於嘗試辛辣的食物感到猶豫。|向當地人問路不要猶豫。"],
    ["switchover", "切換 / 互換", "The switchover to the new system happens tonight.|We planned a driver switchover halfway through the road trip.", "切換到新系統的工作將在今晚進行。|我們計畫在公路旅行中途互換駕駛。"],
    ["honesty", "誠實", "I appreciate your honesty in this matter.|Honesty is the best policy.", "我很感激你在這件事上的誠實。|誠實為上策。"],
    ["unavoidable", "無法避免的", "Some delays are completely unavoidable.|Tension in a group of seven can sometimes be unavoidable.", "有些延誤是完全無法避免的。|七個人的團體中，有時候緊張氣氛是無法避免的。"],
    ["intuitive", "直覺的", "The new software has a very intuitive interface.|Her intuitive sense led her in the right direction.", "這個新軟體有著非常直覺的介面。|她的直覺引導她走向正確的方向。"],
    ["streamlined", "簡化的 / 有效率的", "They streamlined the check-in process at the airport.|We need a streamlined workflow for the office relocation.", "他們簡化了機場的報到流程。|我們需要為辦公室搬遷制定一套有效率的工作流程。"],
    ["implement", "執行 / 實施", "The government will implement new tax laws next year.|We need to implement this strategy immediately.", "政府明年將實施新的稅法。|我們需要立刻執行這項策略。"],
    ["encounter", "遇到 / 遭遇", "Did you encounter any problems at customs?|We had a friendly encounter with the locals.", "你在海關有遇到什麼問題嗎？|我們和當地人有了一次友好的相遇。"],
    ["halve", "減半", "The store decided to halve the price of winter coats.|We managed to halve our travel expenses.", "這家店決定將冬季外套的價格減半。|我們成功把旅行費用減半了。"],
    ["tornado", "龍捲風", "The tornado destroyed several houses in the town.|We had to seek shelter when the tornado warning sounded.", "龍捲風摧毀了鎮上的幾棟房子。|當龍捲風警報響起時，我們必須尋找掩護。"],
    ["distribution", "分發 / 分配", "The distribution of supplies took a long time.|Wealth distribution is a major economic issue.", "物資的分發花了很長的時間。|財富分配是一個重大的經濟問題。"],
    ["effort", "努力", "It takes a lot of effort to learn a new language.|Thanks for your effort in organizing this group trip.", "學習一門新語言需要花費很多努力。|感謝你努力籌辦這次的團體旅行。"],
    ["medium", "中等的 / 媒介", "I would like my steak cooked medium, please.|English is the medium of instruction in this school.", "我的牛排要五分熟，謝謝。|英語是這所學校的教學媒介。"],
    ["enforce", "執行 / 強制", "The police will strictly enforce the speed limit.|It is hard to enforce this new rule.", "警察將嚴格執行速限。|這項新規定很難強制執行。"],
    ["severance", "遣散費", "He received a generous severance package when he was laid off.|The company offered severance pay to the departing employees.", "他被資遣時收到了一筆豐厚的遣散費。|公司向離職的員工提供了遣散費。"],
    ["scientific", "科學的", "There is no scientific evidence to support this claim.|He is conducting a scientific experiment.", "沒有科學證據支持這種說法。|他正在進行一項科學實驗。"],
    ["pesticides", "殺蟲劑", "Organic farmers do not use chemical pesticides.|Wash the fruit carefully to remove any pesticides.", "有機農夫不使用化學殺蟲劑。|仔細清洗水果以去除任何殘留的殺蟲劑。"],
    ["upkeep", "保養 / 維修費", "The upkeep of a large house can be very expensive.|Tenants are responsible for the basic upkeep of the apartment.", "大房子的保養費可能會非常昂貴。|租客有責任進行公寓的基本維護。"],
    ["harmful", "有害的", "Too much sun exposure can be harmful to your skin.|They are removing harmful chemicals from the product.", "過度曝曬陽光對你的皮膚是有害的。|他們正在從產品中去除有害的化學物質。"],
    ["contain", "包含 / 容納", "This box doesn't contain anything valuable.|I couldn't contain my excitement for the US trip.", "這個盒子裡沒裝任何有價值的東西。|我無法抑制我對美國之旅的興奮。"],
    ["lanyards", "掛繩", "All staff members must wear their ID badges on lanyards.|I bought a cool lanyard for my keys.", "所有員工都必須用掛繩佩戴識別證。|我買了一條很酷的掛繩來掛鑰匙。"],
    ["swipe card", "感應卡", "You need a swipe card to enter the building.|I think I lost my hotel swipe card.", "你需要感應卡才能進入這棟大樓。|我想我弄丟了飯店的房卡。"],
    ["quotation", "報價單 / 語錄", "Please send me a formal quotation for the renovation.|He started his speech with a famous quotation.", "請寄給我一份正式的裝修報價單。|他用一句著名的語錄開始了他的演講。"],
    ["apron", "圍裙", "The chef tied his apron before entering the kitchen.|She wore a floral apron while baking cookies.", "主廚在進廚房前繫上了圍裙。|她在烤餅乾時穿了一件碎花圍裙。"],
    ["tough", "困難的 / 堅韌的", "It was a tough decision to make.|The steak was too tough to chew.", "這是一個困難的決定。|這牛排太韌了，咬不動。"],
    ["upset", "難過的 / 打翻", "She was deeply upset by the bad news.|Be careful not to upset the glass of water.", "她因為這個壞消息感到非常難過。|小心別打翻了那杯水。"],
    ["costume", "服裝 / 戲服", "We rented a pirate costume for the Halloween party.|The actors are wearing traditional costumes.", "我們為了萬聖節派對租了一套海盜服裝。|演員們穿著傳統戲服。"],
    ["industry", "工業 / 產業", "The tourism industry is booming right now.|He works in the software industry.", "旅遊產業現在非常繁榮。|他在軟體產業工作。"],
    ["stock", "庫存 / 股票", "We are currently out of stock for this item.|He invested a lot of money in the stock market.", "我們這項商品目前沒有庫存。|他在股票市場投資了很多錢。"],
    ["energetic", "有活力的", "The tour guide was very energetic and fun.|I feel much more energetic after my workout.", "導遊非常有活力而且很有趣。|健身完後我覺得更有活力了。"],
    ["first aid", "急救", "Do you know how to perform basic first aid?|There is a first aid kit in the back of the car.", "你知道如何進行基本的急救嗎？|車子後座有一個急救箱。"],
    ["each other", "彼此", "The seven of us promised to help each other on the trip.|They haven't seen each other in years.", "我們七個人答應在旅途中要互相幫忙。|他們好幾年沒見到彼此了。"],
    ["apparently", "表面上 / 顯然地", "Apparently, the flight is delayed for two hours.|He is apparently the best player on the team.", "顯然地，班機延誤了兩個小時。|他顯然是隊上最好的球員。"],
    ["entrant", "參賽者 / 新加入者", "Every entrant in the marathon received a medal.|Our company is a new entrant in the Asian market.", "馬拉松的每一位參賽者都拿到了一面獎牌。|我們公司是亞洲市場的新加入者。"],
    ["constant", "持續的 / 不斷的", "The machine makes a constant humming noise.|He is under constant pressure at work.", "這台機器發出持續的嗡嗡聲。|他在工作中承受著不斷的壓力。"],
    ["undergone", "經歷過", "The old hotel has undergone massive renovations.|He has undergone three surgeries this year.", "這間老飯店經歷過大規模的翻新。|他今年已經經歷了三次手術。"],
    ["spade", "鏟子", "He used a spade to dig a hole in the garden.|The Ace of Spades is the highest card.", "他用一把鏟子在花園裡挖了個洞。|黑桃A是最大的一張牌。"],
    ["restriction", "限制", "Are there any luggage restrictions for this flight?|The government imposed a new speed restriction.", "這班飛機有任何行李限制嗎？|政府實施了新的速限。"],
    ["dieting", "節食", "She is dieting because she wants to lose weight.|Extreme dieting can be harmful to your health.", "她在節食，因為她想減肥。|極端的節食可能對健康有害。"]
];
