// 這是你的專屬單字資料庫 (words.js)
// 格式：["英文單字", "中文", "英文例句1|英文例句2", "中文例句1|中文例句2"],


const COMPRESSED_DB = [
    ["office relocation", "辦公室搬遷", "The office relocation will be completed by next Monday.|We need to pack our desks before the office relocation.", "辦公室搬遷將在下週一前完成。|我們需要在辦公室搬遷前打包好桌面。"],
    ["reception desk", "接待台", "Please leave the room keys at the reception desk.|Our group of seven gathered at the reception desk.", "請將房間鑰匙留在接待台。|我們七個人在接待台集合。"],
    ["leading supplier", "主要供應商", "They are the leading supplier of sports equipment.|We signed a contract with the leading supplier.", "他們是運動設備的主要供應商。|我們與該主要供應商簽訂了合約。"],
    ["intended listener", "目標聽眾", "Make sure your speech reaches the intended listener.|The advertisement didn't attract its intended listener.", "確保你的演講能傳達給目標聽眾。|這則廣告並沒有吸引到它的目標聽眾。"],
    ["consultation", "諮詢", "I scheduled a quick consultation with the doctor.|The interior designer offers a free consultation.", "我安排了與醫生的快速諮詢。|這位室內設計師提供免費諮詢。"],
    ["upon", "一...就... / 在...之上", "Upon arrival at the airport, we will rent a car.|They agreed upon the budget for the trip.", "一抵達機場，我們就會去租車。|他們就這趟旅行的預算達成了共識。"],
    ["pottery", "陶器", "We bought some beautiful handmade pottery as souvenirs.|He is taking a pottery class on weekends.", "我們買了一些美麗的手工陶器當紀念品。|他週末在上有陶藝課。"],
    ["assess", "評估", "We need to assess the cost of the 10-day trip.|The coach will assess the players' fitness levels.", "我們需要評估這趟 10 天旅行的花費。|教練將評估球員們的體能狀況。"],
    ["vitality", "活力", "Working out weekly helps me maintain my vitality.|The fresh mountain air filled us with vitality.", "每週健身有助於我保持活力。|清新的高山空氣讓我們充滿了活力。"],
    ["command", "命令 / 指揮", "The dog immediately obeyed his command.|She has a good command of the English language.", "那隻狗立刻服從了他的命令。|她精通英語。"],
    ["fixtures", "固定裝置", "We are choosing new lighting fixtures for the living room.|The bathroom fixtures were recently updated.", "我們正在為客廳挑選新的照明燈具。|浴室的固定設備最近剛更新過。"],
    ["naturally", "自然地 / 當然", "Try to speak naturally when ordering food.|Naturally, we will split the bill seven ways.", "點餐時盡量自然地說話。|當然，我們會把帳單分成七份。"],
    ["obligation", "義務 / 責任", "You have no obligation to buy anything in that store.|It is our obligation to clean up before leaving.", "你在那家店裡沒有義務購買任何東西。|離開前清理乾淨是我們的責任。"],
    ["I cannot recommend the store enough", "我極力推薦這家店", "The service was perfect; I cannot recommend the store enough.|If you want a great burger, I cannot recommend the store enough.", "服務太完美了；我極力推薦這家店。|如果你想吃超讚的漢堡，我極力推薦這家店。"],
    ["verge", "邊緣", "I was on the verge of canceling the trip.|The company is on the verge of a major breakthrough.", "我差點就要取消這趟旅行了。|這家公司正處於重大突破的邊緣。"],
    ["a couple of other places", "其他幾個地方", "We plan to visit a couple of other places in New York.|Let's check a couple of other places before deciding.", "我們打算去紐約的其他幾個地方看看。|在決定之前，我們再去其他幾個地方看看吧。"],
    ["lost cause", "注定失敗的事", "Trying to change his mind is a lost cause.|Don't waste energy on a lost cause.", "試圖改變他的想法是白費力氣。|別把精力浪費在注定失敗的事情上。"],
    ["cause", "原因 / 引起", "What was the root cause of the delay?|The bad weather caused our flight to be canceled.", "延誤的根本原因是什麼？|惡劣的天氣導致我們的航班被取消。"],
    ["deal", "交易 / 處理", "We got a great deal on our hotel rooms.|Let me deal with this problem.", "我們的飯店房間拿到了很棒的折扣。|讓我來處理這個問題。"],
    ["disagreed", "不同意", "They strongly disagreed on where to eat tonight.|I disagreed with his proposed itinerary.", "他們對於今晚去哪吃飯意見非常不合。|我不同意他提議的行程。"],
    ["diagnose", "診斷", "The doctor was unable to diagnose his illness.|It is hard to diagnose the problem with the car.", "醫生無法診斷出他的病情。|很難診斷出這輛車的問題出在哪。"],
    ["swiftly", "迅速地", "The waitress moved swiftly to bring our drinks.|We need to act swiftly to catch the train.", "女服務生迅速地把我們的飲料送來。|我們需要迅速行動才趕得上火車。"],
    ["generally", "通常 / 大致上", "Americans generally leave a 15 to 20 percent tip.|I generally wake up at 7 AM.", "美國人通常會留 15% 到 20% 的小費。|我通常早上七點起床。"],
    ["enhancing", "增強 / 提升", "We are looking for ways of enhancing the customer experience.|Reading news is great for enhancing your English.", "我們正在尋找提升顧客體驗的方法。|閱讀新聞對增強你的英文很有幫助。"],
    ["acceptable", "可接受的", "Is this casual outfit acceptable for the restaurant?|The proposed budget is completely acceptable.", "這套休閒服裝去那家餐廳可以接受嗎？|提出來的預算完全可以接受。"],
    ["financial means", "財力", "They lack the financial means to support the project.|Do we have the financial means for a longer trip?", "他們缺乏財力來支持這個專案。|我們有足夠的財力延長旅程嗎？"],
    ["afford", "負擔得起", "We can't afford to miss this flight.|If we split the cost, everyone can afford it.", "我們承擔不起錯過這班飛機的後果。|如果我們平攤費用，每個人都負擔得起。"],
    ["appropriate", "適當的", "Please wear appropriate clothing for the hike.|Is this an appropriate time to call?", "請穿著適當的服裝去健行。|現在打電話是適當的時機嗎？"],
    ["disability", "殘疾", "The museum is fully accessible for people with a disability.|He overcame his physical disability to win the race.", "這間博物館對殘疾人士來說完全無障礙。|他克服了身體的殘障贏得了比賽。"],
    ["senior", "年長的 / 資深的", "Senior citizens get a discount at this cinema.|He is a senior engineer at the tech company.", "年長者在這家電影院可享折扣。|他是那家科技公司的資深工程師。"],
    ["citizen", "公民", "Are you a U.S. citizen?|Every citizen has the right to vote.", "你是美國公民嗎？|每個公民都有投票權。"],
    ["mobility", "機動性", "Regular exercise helps maintain joint mobility.|The new smartphone offers greater mobility for work.", "規律運動有助於維持關節活動力。|新的智慧型手機為工作提供了更大的機動性。"],
    ["caution", "警告 / 謹慎", "Proceed with caution when driving in the snow.|The sign advised caution due to the wet floor.", "在雪地開車請謹慎前行。|告示牌警告因為地板濕滑要小心。"],
    ["consumer", "消費者", "The company aims to protect consumer rights.|Consumer demand for eco-friendly products is rising.", "公司致力於保護消費者權益。|消費者對環保產品的需求正在上升。"],
    ["element", "要素 / 元素", "Trust is a key element in any relationship.|We need to consider the element of surprise.", "信任是任何關係中的關鍵要素。|我們需要把驚喜這個元素考慮進去。"],
    ["placement", "放置 / 佈置", "The product placement in the movie was very obvious.|We discussed the placement of the new sofa.", "這部電影裡的產品置入非常明顯。|我們討論了新沙發的擺放位置。"],
    ["assurance", "保證", "He gave me his assurance that the car would be ready.|I need some assurance before I sign the contract.", "他向我保證車子會準備好。|在簽約之前我需要一些保證。"],
    ["knit belt", "針織腰帶", "She bought a colorful knit belt to match her dress.|A knit belt is comfortable for a long flight.", "她買了一條色彩繽紛的針織腰帶搭配洋裝。|搭長途飛機時繫針織腰帶很舒服。"],
    ["even so", "即使如此", "It's raining heavily; even so, we will go out.|The trip was exhausting. Even so, I had a great time.", "雨下得很大；即使如此，我們還是要出門。|這趟旅行很累人。即使如此，我還是玩得很開心。"],
    ["despite", "儘管", "We arrived on time despite the heavy traffic.|He smiled despite the pain.", "儘管交通擁擠，我們還是準時抵達了。|儘管很痛，他還是笑了。"],
    ["tablet", "平板電腦 / 藥片", "I downloaded some movies onto my tablet for the flight.|Take one tablet twice a day after meals.", "我下載了一些電影到平板電腦裡準備在飛機上看。|這個藥片每天兩次，飯後服用。"],
    ["plant", "植物 / 工廠", "Don't forget to water the plant while I am away.|The car manufacturing plant employs thousands of people.", "我不在的時候別忘了幫植物澆水。|這家汽車製造廠雇用了數千名員工。"],
    ["leakage", "洩漏", "The plumber fixed the water leakage in the bathroom.|There was a sudden gas leakage in the building.", "水管工修好了浴室的漏水。|大樓裡突然發生了瓦斯外洩。"],
    ["combustion", "燃燒", "The engine works by internal combustion.|Combustion produces heat and light.", "引擎是靠內燃運作的。|燃燒會產生熱和光。"],
    ["reaction", "反應", "What was his reaction when you told him the news?|I had a bad allergic reaction to the seafood.", "當你告訴他這個消息時，他有什麼反應？|我對這海鮮產生了嚴重的過敏反應。"],
    ["stripping", "剝離", "They are stripping the old paint off the walls.|Stripping the cables requires a special tool.", "他們正在把牆上的舊油漆剝離掉。|剝開電纜外皮需要特殊工具。"],
    ["etching", "蝕刻", "The artist is famous for his glass etching.|The serial number is made by laser etching.", "這位藝術家以他的玻璃蝕刻聞名。|序號是透過雷射蝕刻製作的。"],
    ["factor", "因素", "Price was a major factor in our decision.|We must consider the weather factor before going out.", "價格是我們決定的一大因素。|出門前我們必須考慮天氣因素。"],
    ["stable", "穩定的", "The patient's condition is now stable.|I need a stable internet connection for my work.", "病人的情況現在穩定了。|我工作需要穩定的網路連線。"],
    ["dosing", "定量 / 劑量分配", "Proper dosing of the medicine is very important.|The machine handles the dosing of the chemicals.", "正確分配藥物劑量非常重要。|這台機器負責化學物質的定量分配。"],
    ["externally", "外部地", "This medicine should only be used externally.|The building was externally damaged by the storm.", "此藥物僅供外用。|這棟建築物外部受到了風暴的破壞。"],
    ["prevent", "預防 / 阻止", "Exercise can help prevent heart disease.|The security guard tried to prevent him from entering.", "運動有助於預防心臟病。|警衛試圖阻止他進入。"],
    ["scaling", "縮放 / 結垢", "The pipes were blocked due to heavy scaling.|Scaling the business will require more capital.", "水管因為嚴重的結垢而堵塞了。|擴張業務將需要更多資金。"],
    ["corrosion", "腐蝕", "The sea air causes rapid corrosion of the metal.|This paint protects the car against corrosion.", "海風會導致金屬迅速腐蝕。|這款油漆可以保護汽車免受腐蝕。"],
    ["growth", "增長 / 發展", "The company has seen rapid growth this year.|Personal growth is just as important as your career.", "公司今年的業績增長非常迅速。|個人成長和你的事業一樣重要。"],
    ["consolidate", "鞏固 / 合併", "Let's consolidate our luggage into one big suitcase.|The two banks decided to consolidate.", "我們把行李合併到一個大行李箱裡吧。|這兩家銀行決定合併。"],
    ["nightstand", "床頭櫃", "I left my phone on the nightstand.|There is a small lamp on the nightstand.", "我把手機留在床頭櫃上了。|床頭櫃上有一盞小燈。"],
    ["mounted", "安裝的 / 固定的", "The TV is securely mounted on the wall.|He easily mounted the horse.", "電視牢固地安裝在牆上。|他輕鬆地跨上了馬。"],
    ["within", "在...之內", "The hotel is within walking distance of the beach.|Please reply within three business days.", "這間飯店在步行即可抵達海灘的距離之內。|請在三個工作天內回覆。"],
    ["reserve", "保留 / 預訂", "I would like to reserve a table for seven people.|We need to reserve our energy for tomorrow's hike.", "我想要預訂一桌七個人的位子。|我們需要為明天的健行保留體力。"],
    ["tense", "緊張的", "The atmosphere in the meeting room was very tense.|Don't be so tense; just relax and enjoy the trip.", "會議室裡的氣氛非常緊張。|別這麼緊張；放輕鬆享受這趟旅行吧。"],
    ["hesitant", "猶豫的", "She was hesitant to try the spicy food.|Don't be hesitant to ask the locals for directions.", "她對於嘗試辛辣的食物感到猶豫。|向當地人問路不要猶豫。"],
    ["switchover", "切換 / 互換", "The switchover to the new system happens tonight.|We planned a driver switchover halfway through the road trip.", "切換到新系統的工作將在今晚進行。|我們計畫在公路旅行中途互換駕駛。"],
    ["honesty", "誠實", "I appreciate your honesty in this matter.|Honesty is the best policy.", "我很感激你在這件事上的誠實。|誠實為上策。"],
    ["unavoidable", "無法避免的", "Some delays are completely unavoidable.|Tension in a group of seven can sometimes be unavoidable.", "有些延誤是完全無法避免的。|七個人的團體中，有時候緊張氣氛是無法避免的。"],
    ["intuitive", "直覺的", "The new software has a very intuitive interface.|Her intuitive sense led her in the right direction.", "這個新軟體有著非常直覺的介面。|她的直覺引導她走向正確的方向。"],
    ["streamlined", "簡化的 / 有效率的", "They streamlined the check-in process at the airport.|We need a streamlined workflow for the office relocation.", "他們簡化了機場的報到流程。|我們需要為辦公室搬遷制定一套有效率的工作流程。"],
    ["implement", "執行 / 實施", "The government will implement new tax laws next year.|We need to implement this strategy immediately.", "政府明年將實施新的稅法。|我們需要立刻執行這項策略。"],
    ["encounter", "遇到 / 遭遇", "Did you encounter any problems at customs?|We had a friendly encounter with the locals.", "你在海關有遇到什麼問題嗎？|我們和當地人有了一次友好的相遇。"],
    ["halve", "減半", "The store decided to halve the price of winter coats.|We managed to halve our travel expenses.", "這家店決定將冬季外套的價格減半。|我們成功把旅行費用減半了。"],
    ["tornado", "龍捲風", "The tornado destroyed several houses in the town.|We had to seek shelter when the tornado warning sounded.", "龍捲風摧毀了鎮上的幾棟房子。|當龍捲風警報響起時，我們必須尋找掩護。"],
    ["distribution", "分發 / 分配", "The distribution of supplies took a long time.|Wealth distribution is a major economic issue.", "物資的分發花了很長的時間。|財富分配是一個重大的經濟問題。"],
    ["effort", "努力", "It takes a lot of effort to learn a new language.|Thanks for your effort in organizing this group trip.", "學習一門新語言需要花費很多努力。|感謝你努力籌辦這次的團體旅行。"],
    ["medium", "中等的 / 媒介", "I would like my steak cooked medium, please.|English is the medium of instruction in this school.", "我的牛排要五分熟，謝謝。|英語是這所學校的教學媒介。"],
    ["enforce", "執行 / 強制", "The police will strictly enforce the speed limit.|It is hard to enforce this new rule.", "警察將嚴格執行速限。|這項新規定很難強制執行。"],
    ["severance", "遣散費", "He received a generous severance package when he was laid off.|The company offered severance pay to the departing employees.", "他被資遣時收到了一筆豐厚的遣散費。|公司向離職的員工提供了遣散費。"],
    ["scientific", "科學的", "There is no scientific evidence to support this claim.|He is conducting a scientific experiment.", "沒有科學證據支持這種說法。|他正在進行一項科學實驗。"],
    ["pesticides", "殺蟲劑", "Organic farmers do not use chemical pesticides.|Wash the fruit carefully to remove any pesticides.", "有機農夫不使用化學殺蟲劑。|仔細清洗水果以去除任何殘留的殺蟲劑。"],
    ["upkeep", "保養 / 維修費", "The upkeep of a large house can be very expensive.|Tenants are responsible for the basic upkeep of the apartment.", "大房子的保養費可能會非常昂貴。|租客有責任進行公寓的基本維護。"],
    ["harmful", "有害的", "Too much sun exposure can be harmful to your skin.|They are removing harmful chemicals from the product.", "過度曝曬陽光對你的皮膚是有害的。|他們正在從產品中去除有害的化學物質。"],
    ["contain", "包含 / 容納", "This box doesn't contain anything valuable.|I couldn't contain my excitement for the US trip.", "這個盒子裡沒裝任何有價值的東西。|我無法抑制我對美國之旅的興奮。"],
    ["lanyards", "掛繩", "All staff members must wear their ID badges on lanyards.|I bought a cool lanyard for my keys.", "所有員工都必須用掛繩佩戴識別證。|我買了一條很酷的掛繩來掛鑰匙。"],
    ["swipe card", "感應卡", "You need a swipe card to enter the building.|I think I lost my hotel swipe card.", "你需要感應卡才能進入這棟大樓。|我想我弄丟了飯店的房卡。"],
    ["quotation", "報價單 / 語錄", "Please send me a formal quotation for the renovation.|He started his speech with a famous quotation.", "請寄給我一份正式的裝修報價單。|他用一句著名的語錄開始了他的演講。"],
    ["apron", "圍裙", "The chef tied his apron before entering the kitchen.|She wore a floral apron while baking cookies.", "主廚在進廚房前繫上了圍裙。|她在烤餅乾時穿了一件碎花圍裙。"],
    ["tough", "困難的 / 堅韌的", "It was a tough decision to make.|The steak was too tough to chew.", "這是一個困難的決定。|這牛排太韌了，咬不動。"],
    ["upset", "難過的 / 打翻", "She was deeply upset by the bad news.|Be careful not to upset the glass of water.", "她因為這個壞消息感到非常難過。|小心別打翻了那杯水。"],
    ["costume", "服裝 / 戲服", "We rented a pirate costume for the Halloween party.|The actors are wearing traditional costumes.", "我們為了萬聖節派對租了一套海盜服裝。|演員們穿著傳統戲服。"],
    ["industry", "工業 / 產業", "The tourism industry is booming right now.|He works in the software industry.", "旅遊產業現在非常繁榮。|他在軟體產業工作。"],
    ["stock", "庫存 / 股票", "We are currently out of stock for this item.|He invested a lot of money in the stock market.", "我們這項商品目前沒有庫存。|他在股票市場投資了很多錢。"],
    ["energetic", "有活力的", "The tour guide was very energetic and fun.|I feel much more energetic after my workout.", "導遊非常有活力而且很有趣。|健身完後我覺得更有活力了。"],
    ["first aid", "急救", "Do you know how to perform basic first aid?|There is a first aid kit in the back of the car.", "你知道如何進行基本的急救嗎？|車子後座有一個急救箱。"],
    ["each other", "彼此", "The seven of us promised to help each other on the trip.|They haven't seen each other in years.", "我們七個人答應在旅途中要互相幫忙。|他們好幾年沒見到彼此了。"],
    ["apparently", "表面上 / 顯然地", "Apparently, the flight is delayed for two hours.|He is apparently the best player on the team.", "顯然地，班機延誤了兩個小時。|他顯然是隊上最好的球員。"],
    ["entrant", "參賽者 / 新加入者", "Every entrant in the marathon received a medal.|Our company is a new entrant in the Asian market.", "馬拉松的每一位參賽者都拿到了一面獎牌。|我們公司是亞洲市場的新加入者。"],
    ["constant", "持續的 / 不斷的", "The machine makes a constant humming noise.|He is under constant pressure at work.", "這台機器發出持續的嗡嗡聲。|他在工作中承受著不斷的壓力。"],
    ["undergone", "經歷過", "The old hotel has undergone massive renovations.|He has undergone three surgeries this year.", "這間老飯店經歷過大規模的翻新。|他今年已經經歷了三次手術。"],
    ["spade", "鏟子", "He used a spade to dig a hole in the garden.|The Ace of Spades is the highest card.", "他用一把鏟子在花園裡挖了個洞。|黑桃A是最大的一張牌。"],
    ["restriction", "限制", "Are there any luggage restrictions for this flight?|The government imposed a new speed restriction.", "這班飛機有任何行李限制嗎？|政府實施了新的速限。"],
    ["dieting", "節食", "She is dieting because she wants to lose weight.|Extreme dieting can be harmful to your health.", "她在節食，因為她想減肥。|極端的節食可能對健康有害。"]
    ["stressful", "有壓力的", "Planning a trip for seven people can be quite stressful.|My new job is very stressful.", "為七個人規劃旅行可能會滿有壓力的。|我的新工作非常有壓力。"],
    ["enrollment", "註冊 / 加入", "University enrollment has increased this year.|The gym is offering free enrollment this month.", "今年的大學註冊人數增加了。|健身房這個月提供免費加入。"],
    ["refund", "退款", "I would like to request a full refund for this ticket.|The store's policy does not allow cash refunds.", "我想要申請這張票的全額退款。|這家店的政策不允許現金退款。"],
    ["emission", "排放", "The factory must reduce its carbon emission.|New cars have lower exhaust emissions.", "這家工廠必須減少其碳排放。|新車的廢氣排放量較低。"],
    ["inclusion", "包括 / 包含", "The inclusion of breakfast in the hotel price is great.|We strive for diversity and inclusion in our office.", "飯店價格包含早餐，這真是太棒了。|我們致力於辦公室的多元與包容。"],
    ["for instance", "例如", "Many cities, for instance New York, never sleep.|There are many benefits to exercise; for instance, better sleep.", "許多城市，例如紐約，是個不夜城。|運動有很多好處；例如，更好的睡眠品質。"],
    ["in spite of", "儘管", "In spite of the rain, we went out for a walk.|He won the match in spite of his injury.", "儘管下雨，我們還是出去散步了。|儘管受傷，他還是贏得了比賽。"],
    ["as for", "至於 / 關於", "As for me, I prefer coffee over tea.|As for the budget, we will discuss it tomorrow.", "至於我，我比較喜歡咖啡勝過茶。|關於預算，我們明天再討論。"],
    ["now that", "既然 / 由於", "Now that we are here, let's take a photo.|Now that it's raining, we should stay indoors.", "既然我們都來了，就拍張照吧。|由於下雨了，我們應該待在室內。"],
    ["discipline", "紀律 / 學科", "It takes strict discipline to work out every week.|Sociology is a fascinating academic discipline.", "每週健身需要嚴格的紀律。|社會學是一門迷人的學科。"],
    ["format", "版式 / 格式", "The file format must be a PDF.|I don't like the new format of this TV show.", "檔案格式必須是 PDF。|我不喜歡這個電視節目的新版式（形態）。"],
    ["stroll", "散步 / 閒逛", "We took a leisurely stroll along the beach.|Let's stroll around the park after dinner.", "我們沿著海灘悠閒地散步。|晚餐後我們去公園周圍閒逛一下吧。"],
    ["recipients", "收件人", "Please enter the email addresses of the recipients.|The recipients of the scholarship will be announced soon.", "請輸入收件人的電子郵件地址。|獎學金的受獎人（收件人）很快就會公布。"],
    ["simultaneously", "同時地", "The game will be broadcast simultaneously on TV and online.|Two flights arrived simultaneously.", "這場比賽將在電視和網路上同時播出。|兩架航班同時抵達了。"],
    ["exception", "例外", "There is an exception to every rule.|With the exception of John, everyone was present.", "每個規則都有例外。|除了約翰（作為例外），每個人都出席了。"],
    ["exceptionally", "非常地", "The weather has been exceptionally cold this winter.|She is an exceptionally talented designer.", "今年冬天的天氣異常寒冷。|她是一位非常有才華的設計師。"],
    ["incidentally", "順便一提 / 偶然地", "Incidentally, do you know where the restroom is?|The discovery was made incidentally during a routine test.", "順便一提，你知道洗手間在哪裡嗎？|這個發現是在例行測試中偶然獲得的。"],
    ["artificially", "人工地", "The room was artificially cooled by the AC.|These snacks are artificially flavored.", "這個房間由冷氣人工降溫。|這些零食是人工調味的。"],
    ["sculptures", "雕塑品", "The museum has a beautiful collection of marble sculptures.|He makes metal sculptures from recycled materials.", "這間博物館收藏了美麗的大理石雕塑。|他用回收材料製作金屬雕塑。"],
    ["outskirts", "郊區", "They live on the outskirts of Los Angeles.|We found a cheap motel on the outskirts of town.", "他們住在洛杉磯的郊區。|我們在小鎮郊區找到了一間便宜的汽車旅館。"],
    ["catalog", "目錄", "You can order these items directly from our catalog.|The library has a huge digital catalog.", "你可以直接從我們的目錄訂購這些商品。|圖書館有著龐大的數位目錄。"],
    ["malfunction", "故障", "A technical malfunction caused the train to stop.|If there is a malfunction, please press the emergency button.", "技術故障導致火車停駛。|如果發生故障，請按下緊急按鈕。"],
    ["resume", "履歷表 / 重新開始", "Please send your resume to the HR department.|The game will resume after a short break.", "請將您的履歷表寄給人資部門。|比賽將在短暫休息後重新開始。"],
    ["otherwise", "否則", "We need to leave now, otherwise we will miss the flight.|I'm busy today; otherwise, I would join you.", "我們現在必須離開，否則會錯過航班。|我今天很忙；否則我就會加入你們了。"],
    ["identical", "完全相同的", "The two suitcases look completely identical.|They are wearing identical shirts.", "這兩個行李箱看起來完全一模一樣。|他們穿著完全相同的襯衫。"],
    ["adventure", "冒險", "Our road trip across America was a great adventure.|Are you ready for your next adventure?", "我們橫跨美國的公路旅行是一場超棒的冒險。|你準備好迎接下一次的冒險了嗎？"],
    ["advanced", "先進的 / 高階的", "This class is for students with advanced English skills.|The hospital uses advanced medical equipment.", "這堂課是為擁有高階英文能力的學生開設的。|這間醫院使用先進的醫療設備。"],
    ["idealistic", "理想主義的", "When I was young, I was very idealistic.|His plan sounds good, but it's a bit too idealistic.", "當我年輕時，我非常理想主義。|他的計畫聽起來不錯，但有點太過理想化了。"],
    ["critic", "評論家", "The movie received high praise from a famous film critic.|He works as a food critic for a magazine.", "這部電影受到了一位著名影評人的高度讚揚。|他在一家雜誌擔任美食評論家。"],
    ["critical", "批評的 / 關鍵的", "It is critical that we arrive at the airport on time.|The movie received critical praise.", "我們準時抵達機場是非常關鍵的。|這部電影受到了評論家（批評的）讚揚。"],
    ["suitable", "適合的", "This movie is not suitable for children.|We need to find a suitable time for the meeting.", "這部電影不適合兒童觀看。|我們需要找個適合的時間開會。"],
    ["naive", "天真的", "It was naive of me to trust him so easily.|Don't be so naive; nobody gives away free money.", "我這麼輕易就相信他真是太天真了。|別這麼天真；沒有人會白白送錢。"],
    ["blacksmith", "鐵匠", "The blacksmith forged a new sword from the metal.|We visited an old blacksmith shop in the village.", "鐵匠用金屬鍛造了一把新劍。|我們參觀了村子裡一間古老的鐵匠鋪。"],
    ["textile weaving", "紡織編織", "She is learning traditional textile weaving.|This region is famous for its textile weaving industry.", "她正在學習傳統的紡織編織。|這個地區以其紡織編織產業聞名。"],
    ["accessible", "可使用的 / 無障礙的", "The museum is fully accessible to wheelchair users.|This information is easily accessible online.", "這間博物館對輪椅使用者完全無障礙。|這些資訊在網路上很容易取得（可使用）。"],
    ["interpreter", "口譯員", "We hired an interpreter for the business meeting.|She works as an interpreter for the United Nations.", "我們為這場商務會議聘請了一位口譯員。|她在聯合國擔任口譯員。"],
    ["involved", "有關的 / 牽涉在內的", "I don't want to get involved in their argument.|Many people were involved in the project.", "我不想捲入他們的爭吵中。|很多人參與了（牽涉在）這個專案。"],
    ["comprised", "包含 / 組成", "The team is comprised of seven members.|The exhibition is comprised of modern sculptures.", "這個團隊由七名成員組成。|這個展覽包含了現代雕塑。"],
    ["wheelchair", "輪椅", "The hotel requested a room accessible by wheelchair.|My grandmother uses a wheelchair to get around.", "這間飯店要求了一間輪椅可進入的無障礙房間。|我祖母坐輪椅代步。"],
    ["impeller", "葉輪", "The pump's impeller needs to be replaced.|An impeller accelerates the fluid outward.", "幫浦的葉輪需要更換了。|葉輪將流體向外加速。"],
    ["suction", "抽吸", "The vacuum cleaner has strong suction power.|The dentist used a suction tube during the procedure.", "這台吸塵器有很強的吸力。|牙醫在手術過程中使用了抽吸管。"],
    ["discharge", "釋放 / 排放", "The factory was fined for an illegal discharge of chemicals.|He was discharged from the hospital yesterday.", "這家工廠因為非法排放化學物質而被罰款。|他昨天出院（被釋放）了。"],
    ["refining", "提煉 / 精煉", "The company specializes in refining oil.|We are constantly refining our design process.", "這家公司專門從事石油提煉。|我們不斷精煉我們的設計流程。"],
    ["spool", "線軸", "She bought a spool of red thread for sewing.|The wire is wound around a large wooden spool.", "她買了一個紅線軸來縫紉。|電線纏繞在一個大木製線軸上。"],
    ["radiation", "輻射", "High levels of radiation are dangerous to humans.|The machine uses low-dose radiation.", "高濃度的輻射對人體是危險的。|這台機器使用低劑量輻射。"],
    ["compared", "比較的", "Compared to last year, our sales have doubled.|This hotel is much cheaper compared to the others.", "與去年相比，我們的銷售額翻倍了。|這間飯店與其他的相比便宜很多。"],
    ["suspect", "懷疑 / 嫌疑犯", "I suspect that we are going the wrong way.|The police have arrested a suspect in the robbery.", "我懷疑我們走錯路了。|警方逮捕了一名搶劫案的嫌疑犯。"],
    ["panel discussions", "小組討論", "There will be several panel discussions at the symposium.|She participated in two panel discussions yesterday.", "研討會上將有幾場小組討論。|她昨天參加了兩場小組討論。"],
    ["appeal", "呼籲 / 吸引力", "This dark movie has a strong appeal to me.|The charity made an urgent appeal for donations.", "這部黑暗的電影對我有強烈的吸引力。|該慈善機構發出了緊急的捐款呼籲。"],
    ["indigenous", "本土的 / 原住民的", "We visited an indigenous village in the mountains.|The kangaroo is indigenous to Australia.", "我們參觀了山裡的一個原住民村落。|袋鼠是澳洲特有（本土）的動物。"],
    ["domestic", "國內的 / 家庭的", "Are we at the domestic or international terminal?|They focus on domestic tourism this year.", "我們現在是在國內航廈還是國際航廈？|他們今年的重點放在國內旅遊。"],
    ["interest", "興趣 / 利息", "I have a strong interest in learning English.|The bank offers a low interest rate for loans.", "我對學習英文有濃厚的興趣。|銀行為貸款提供低利率（利息）。"],
    ["aligned", "對齊的", "Make sure the text is aligned to the left.|Our goals are perfectly aligned.", "確保文字靠左對齊。|我們的目標完全一致（對齊）。"],
    ["behalf", "代表 / 利益", "I am speaking on behalf of my team.|The lawyer acted on behalf of his client.", "我代表我的團隊發言。|律師代表他的客戶行事。"],
    ["vintage", "復古的 / 經典的", "She loves shopping for vintage clothes in thrift stores.|He bought a vintage camera at the flea market.", "她喜歡在二手商店買復古衣物。|他在跳蚤市場買了一台經典的復古相機。"],
    ["dedicated", "專注的 / 奉獻的", "She is a dedicated teacher who loves her students.|This room is dedicated to fitness.", "她是一位熱愛學生的專注老師。|這個房間專門（專注）用來健身。"],
    ["preloved", "二手的", "I bought a preloved designer bag online.|Preloved items are often cheaper and more eco-friendly.", "我在網路上買了一個二手的名牌包。|二手商品通常比較便宜且更環保。"],
    ["sourcing", "採購", "He is responsible for the sourcing of raw materials.|Ethical sourcing is a priority for our brand.", "他負責原料的採購。|合乎道德的採購是我們品牌的優先考量。"],
    ["bite", "咬 / 一口", "I just need a quick bite before we head out.|Does your dog bite?", "我們出發前我只需要隨便吃一口東西。|你的狗會咬人嗎？"],
    ["varies", "變化 / 差異", "The room price varies depending on the season.|The quality of the food varies from day to day.", "房價會根據季節有所變化。|這家店食物的品質每天都不太一樣。"],
    ["inclusive", "包含的 / 包容的", "The resort package is all-inclusive.|We want to build a more inclusive society.", "這間度假村的套裝行程是全包式的（包含一切的）。|我們想建立一個更具包容性的社會。"],
    ["collectibles", "收藏品", "He spends a lot of money on rare collectibles.|The shop sells vintage toys and other collectibles.", "他花了很多錢在稀有收藏品上。|這家店販售復古玩具和其他收藏品。"],
    ["desirable", "理想的 / 令人嚮往的", "This neighborhood is a very desirable place to live.|It is desirable to have a flexible schedule.", "這個社區是個非常令人嚮往的居住地。|擁有彈性的行程是很理想的。"],
    ["sustainability", "永續性", "Environmental sustainability is our core value.|Many brands are now focusing on sustainability.", "環境永續性是我們的核心價值。|許多品牌現在都專注於永續發展。"],
    ["reputation", "名聲", "That restaurant has a reputation for terrible service.|He has a solid reputation in the design industry.", "那家餐廳以服務極差而「聞名」（名聲不好）。|他在設計界有著良好的名聲。"],
    ["instantly", "立即地", "I recognized her instantly when she walked in.|The pain disappeared almost instantly.", "她一走進來我立刻就認出她了。|疼痛幾乎立刻消失了。"],
    ["optimally", "最理想地", "The system is running optimally now.|You need to rest to perform optimally.", "系統現在正以最理想的狀態運行。|你需要休息才能有最理想的表現。"],
    ["explicitly", "明確地", "I explicitly told him not to touch my computer.|The rules are explicitly stated in the manual.", "我明確地告訴過他不要碰我的電腦。|規則在手冊中有明確的說明。"],
    ["similarly", "同樣地", "He dressed similarly to his older brother.|The two machines operate similarly.", "他的穿著和他哥哥同樣地相似。|這兩台機器的運作方式同樣相似。"],
    ["dissatisfied", "不滿意的", "We were dissatisfied with the quality of the food.|If you are dissatisfied, you can get a refund.", "我們對食物的品質感到不滿意。|如果您不滿意，可以申請退款。"],
    ["value", "價值 / 重視", "This house has gone up in value.|I highly value your opinion on this design.", "這棟房子的價值上升了。|我非常重視你對這個設計的意見。"],
    ["rude", "無禮的", "It is rude to point your finger at someone.|The waiter was very rude to us.", "用手指著別人是很無禮的。|那個服務生對我們非常無禮。"],
    ["recent", "最近的", "Have you seen any good movies in recent weeks?|My recent trip to the US was amazing.", "你最近幾週有看什麼好電影嗎？|我最近的美國之旅棒極了。"],
    ["antique", "古董的 / 古董", "My mother loves collecting antique furniture.|There is an antique shop at the corner.", "我媽媽喜歡收集古董家具。|轉角處有一間古董店。"],
    ["acquisition", "獲得 / 收購", "The company announced the acquisition of a rival firm.|Language acquisition is easier for young children.", "公司宣布收購了一家競爭對手。|語言的獲得對幼兒來說比較容易。"],
    ["solicit funding", "募集資金", "The startup is trying to solicit funding from investors.|We need to solicit funding for the new library.", "這家新創公司正試圖向投資者募集資金。|我們需要為新圖書館募集資金。"],
    ["enabled", "啟動的 / 啟用的", "Make sure Wi-Fi is enabled on your phone.|The new update enabled several useful features.", "確保你的手機已啟用 Wi-Fi。|新的更新啟用了幾個實用的功能。"],
    ["inner-city school", "市內學校", "He teaches math at an inner-city school.|Inner-city schools often face funding challenges.", "他在一所市內學校教數學。|市內學校通常面臨資金挑戰。"],
    ["suitcase", "行李箱", "I couldn't fit all my clothes in one suitcase.|Please make sure your suitcase is locked.", "我無法把所有的衣服塞進一個行李箱裡。|請確保你的行李箱上鎖了。"],
    ["visibility", "能見度", "The thick fog reduced visibility to near zero.|The new marketing campaign increased brand visibility.", "濃霧讓能見度降到幾乎為零。|新的行銷活動增加了品牌的能見度。"],
    ["summit", "頂峰 / 高峰會", "It took us five hours to reach the mountain summit.|The leaders met at the global summit.", "我們花了五個小時才抵達山頂（頂峰）。|各國領袖在全球高峰會上會面。"],
    ["newcomer", "新手 / 初學者", "She is a newcomer to the design team.|As a newcomer, he asked a lot of questions.", "她是設計團隊的新手。|作為一個新手，他問了很多問題。"],
    ["scene", "場景", "The opening scene of the movie is spectacular.|The police arrived at the crime scene.", "這部電影的開場場景非常壯觀。|警方抵達了犯罪現場。"],
    ["attracting", "吸引", "The beautiful beach is attracting many tourists.|They are attracting new customers with low prices.", "美麗的海灘正吸引著許多遊客。|他們正以低價吸引新顧客。"],
    ["extracting", "提取 / 萃取", "Extracting oil from the ground is expensive.|They are extracting the juice from the apples.", "從地底下提取石油是很昂貴的。|他們正在萃取蘋果汁。"],
    ["simplifying", "簡化", "We are simplifying the checkout process for our app.|Simplifying your life can reduce stress.", "我們正在簡化我們 App 的結帳流程。|簡化你的生活可以減少壓力。"],
    ["funeral", "葬禮", "He wore a black suit to the funeral.|The funeral will be held tomorrow morning.", "他穿著黑色西裝參加葬禮。|葬禮將於明天上午舉行。"],
    ["leisure", "休閒", "What do you like to do in your leisure time?|We walked along the beach at our leisure.", "你在休閒時間喜歡做什麼？|我們悠閒地沿著海灘散步。"],
    ["navigate", "導航", "I'll drive, and you can navigate using Google Maps.|It's hard to navigate this huge airport.", "我來開車，你可以用 Google 地圖導航。|要在這個巨大的機場裡導航（找路）很困難。"],
    ["faucet", "水龍頭", "Please turn off the faucet while brushing your teeth.|The bathroom faucet is leaking again.", "刷牙時請關掉水龍頭。|浴室的水龍頭又漏水了。"],
    ["water dispenser", "飲水機", "You can refill your bottle at the water dispenser.|The office water dispenser is empty.", "你可以在飲水機裝滿你的水瓶。|辦公室的飲水機空了。"],
    ["barriers", "障礙物", "The police set up barriers around the building.|Language can be a barrier when traveling.", "警察在建築物周圍設置了路障。|旅行時，語言可能成為一種障礙。"],
    ["spillage", "溢出 / 溢出量", "Please clean up the coffee spillage immediately.|The lid prevents liquid spillage.", "請立刻清理溢出的咖啡。|這個蓋子可以防止液體溢出。"],
    ["armrests", "扶手", "The airplane seats have very narrow armrests.|Please lower the armrests before takeoff.", "飛機座椅的扶手非常狹窄。|起飛前請放下扶手。"],
    ["outlined", "大綱 / 概述", "The manager outlined the new project to the team.|The book outlined the history of the country.", "經理向團隊概述了新專案。|這本書概述了這個國家的歷史。"],
    ["reusable", "可重複使用的", "I always carry a reusable shopping bag.|These cups are eco-friendly and reusable.", "我總是隨身攜帶可重複使用的購物袋。|這些杯子很環保而且可重複使用。"],
    ["uncover", "揭露", "The journalist tried to uncover the truth.|They uncovered a hidden treasure in the cave.", "記者試圖揭露真相。|他們在洞穴中發現（揭開）了隱藏的寶藏。"],
    ["depicting", "描繪", "The painting is depicting a beautiful sunset.|The movie is depicting the life of a famous artist.", "這幅畫描繪著美麗的夕陽。|這部電影描繪了一位著名藝術家的一生。"],
    ["intake form", "入學表格 / 初診表格", "Please fill out this intake form before seeing the doctor.|New students must submit an intake form.", "看醫生前請先填寫這份初診表格（收件表）。|新生必須提交一份入學表格。"],
    ["commitment", "承諾 / 保證", "We made a commitment to finish the project on time.|Marriage is a lifelong commitment.", "我們承諾會準時完成專案。|婚姻是一輩子的承諾。"]
    ["rectified", "糾正", "The error in the report was quickly rectified.|Please ensure this mistake is rectified before tomorrow.", "報告中的錯誤很快就被糾正了。|請確保這個錯誤在明天之前被糾正。"],
    ["glitch", "小故障 / 小毛病", "There was a minor glitch in the booking system.|My phone is experiencing a weird software glitch.", "訂票系統出現了一個小故障。|我的手機遇到了一個奇怪的軟體小毛病。"],
    ["minor", "次要的 / 輕微的", "It's just a minor problem, so don't worry.|He suffered only minor injuries in the accident.", "這只是一個次要的問題，別擔心。|他在車禍中只受了輕傷。"],
    ["promptly", "迅速地 / 準時地", "The meeting will start promptly at 9 AM.|Please reply to this email promptly.", "會議將在早上九點準時開始。|請迅速回覆這封電子郵件。"],
    ["guidance", "指導", "I need your professional guidance on this project.|The tour guide provided excellent guidance.", "我需要你對這個專案的專業指導。|導遊提供了非常出色的指導。"],
    ["revamping", "改造 / 翻新", "The company is revamping its website.|We are revamping our living room this summer.", "這家公司正在改造其網站。|我們今年夏天要翻新客廳。"],
    ["liability", "責任 / 義務", "The company accepts no liability for lost items.|He has a heavy financial liability.", "本公司對遺失物品不承擔任何責任。|他有沉重的財務義務（負債）。"],
    ["dedication", "貢獻 / 奉獻", "We appreciate your hard work and dedication.|It takes a lot of dedication to learn a new language.", "我們感謝你的辛勤工作與貢獻。|學習一門新語言需要大量的奉獻與努力。"],
    ["farewell party", "歡送會", "We threw a farewell party for our retiring boss.|Are you coming to Sarah's farewell party tonight?", "我們為即將退休的老闆舉辦了一場歡送會。|你今晚會來參加 Sarah 的歡送會嗎？"],
    ["symposium", "研討會", "He was invited to speak at an international symposium.|The symposium will focus on environmental issues.", "他受邀在國際研討會上演講。|這場研討會將聚焦於環境議題。"],
    ["due to", "由於", "The flight was delayed due to bad weather.|His success is due to his hard work.", "由於天氣惡劣，航班延誤了。|他的成功歸功於（由於）他的努力工作。"],
    ["giant", "巨大的 / 巨人", "We saw a giant billboard on the highway.|The story is about a friendly giant.", "我們在高速公路上看到了一個巨大的廣告看板。|這個故事是關於一個友善的巨人。"],
    ["due", "到期的 / 預期的", "When is the rent due?|The baby is due in November.", "房租什麼時候到期？|寶寶預產期（預期）在十一月。"],
    ["cushion", "坐墊 / 緩衝", "I bought a new cushion for the sofa.|Airbags provide a safety cushion in a car crash.", "我為沙發買了一個新坐墊。|安全氣囊在車禍中提供了安全緩衝。"],
    ["avocado", "酪梨", "I love having avocado on my toast.|Avocados are rich in healthy fats.", "我喜歡在吐司上放酪梨。|酪梨富含健康的脂肪。"],
    ["prawn", "明蝦 / 大蝦", "We ordered garlic butter prawns for dinner.|How much is a kilogram of fresh prawns?", "我們晚餐點了蒜香奶油明蝦。|一公斤新鮮明蝦多少錢？"],
    ["absent", "缺席的", "He was absent from work due to illness.|Three students are absent today.", "他因為生病而缺席了工作。|今天有三個學生缺席。"],
    ["recipe", "食譜", "Can you share the recipe for this cake?|Hard work is the best recipe for success.", "你能分享這個蛋糕的食譜嗎？|努力工作是成功的最佳秘訣（食譜）。"],
    ["reluctant", "不情願的", "She was reluctant to leave her comfortable bed.|I am reluctant to spend that much money on shoes.", "她很不情願離開她舒適的床。|我很不情願花那麼多錢買鞋。"],
    ["pitiful", "可憐的 / 令人同情的", "The stray dog looked so pitiful in the rain.|His excuse for being late was truly pitiful.", "那隻流浪狗在雨中看起來好可憐。|他遲到的藉口實在是太令人同情（可悲）了。"],
    ["dismayed", "感到沮喪的", "We were dismayed by the poor service at the hotel.|He was deeply dismayed when he failed the test.", "我們對飯店糟糕的服務感到很沮喪。|當他考試不及格時，他感到深深的沮喪。"],
    ["spices", "香料 / 調味料", "Indian food uses a lot of different spices.|I need to buy some spices for the soup.", "印度菜使用很多不同的香料。|我需要買一些調味料來煮湯。"],
    ["to reach an agreement", "達成協議", "It took them three days to reach an agreement.|Both companies finally managed to reach an agreement.", "他們花了三天才達成協議。|兩家公司最後終於成功達成協議。"],
    ["reach an item", "伸手拿物品", "Could you help me reach that item on the top shelf?|He stretched his arm to reach an item on the desk.", "你能幫我伸手拿頂層架子上的那個物品嗎？|他伸長手臂去拿桌上的一件物品。"],
    ["come to a conclusion", "得出結論", "After a long debate, we have come to a conclusion.|Did you come to a conclusion about your travel plans?", "經過漫長的辯論，我們已經得出結論。|你對你的旅行計畫得出結論了嗎？"],
    ["hold a meeting", "舉行會議", "We need to hold a meeting to discuss the budget.|The manager will hold a meeting tomorrow morning.", "我們需要舉行會議來討論預算。|經理明天早上將舉行會議。"],
    ["metropolitan", "大都會的", "Taipei is a busy metropolitan area.|We visited the Metropolitan Museum of Art in New York.", "台北是一個繁忙的大都會地區。|我們參觀了紐約的大都會藝術博物館。"],
    ["pay an invoice", "支付發票 / 付帳單", "Please pay this invoice within 30 days.|I need to pay an invoice for the office supplies.", "請在 30 天內支付這張發票。|我需要為辦公用品支付一張發票。"],
    ["components", "成分 / 零件", "He bought some electronic components for his project.|Trust and respect are key components of a good team.", "他為他的專案買了一些電子零件。|信任和尊重是好團隊的關鍵成分。"],
    ["throughout", "遍及 / 自始至終", "It rained heavily throughout the night.|The brand is famous throughout the world.", "昨晚徹夜（自始至終）下著大雨。|這個品牌舉世（遍及世界）聞名。"],
    ["reach", "到達 / 聯絡", "We finally reached the hotel after a 10-hour drive.|You can reach me at this phone number.", "開了 10 小時的車後，我們終於到達了飯店。|你可以透過這個電話號碼聯絡到我。"],
    ["migrate", "遷徙 / 轉移", "Many birds migrate south for the winter.|We need to migrate all the data to the new server.", "許多鳥類在冬天向南遷徙。|我們需要將所有資料轉移到新伺服器。"],
    ["inherited", "遺傳的 / 繼承的", "She inherited the house from her grandfather.|He has an inherited heart condition.", "她從祖父那裡繼承了這棟房子。|他有遺傳性的心臟病。"],
    ["comedians", "喜劇演員", "Stand-up comedians perform live in this club.|He is one of my favorite comedians.", "單口喜劇演員在這家俱樂部進行現場表演。|他是我最喜歡的喜劇演員之一。"],
    ["sense", "感覺 / 意義", "He has a great sense of humor.|This sentence doesn't make any sense to me.", "他有很好的幽默感。|這句話對我來說毫無意義（說不通）。"],
    ["quarterly", "每季的", "The company publishes a quarterly financial report.|We have a quarterly team building event.", "這家公司發布每季的財務報告。|我們每季都有一次團隊建立活動。"],
    ["readership", "讀者群", "This magazine has a very large readership.|The author wants to expand his international readership.", "這本雜誌擁有非常龐大的讀者群。|這位作者想擴大他的國際讀者群。"],
    ["complimented", "稱讚", "She complimented me on my new haircut.|The chef was highly complimented for the meal.", "她稱讚了我的新髮型。|主廚因為這頓飯受到了高度稱讚。"],
    ["measure", "測量 / 措施", "We need to measure the dimensions of the room.|The government took strict measures to control traffic.", "我們需要測量房間的尺寸。|政府採取了嚴格的措施來控制交通。"],
    ["accidentally", "不小心地 / 意外地", "I accidentally deleted the important file.|He accidentally spilled coffee on his shirt.", "我不小心刪除了重要的檔案。|他意外地把咖啡灑在了襯衫上。"],
    ["orientation", "新生訓練 / 定向", "The university orientation starts next Monday.|The building's orientation allows for natural sunlight.", "大學的新生訓練下週一開始。|這棟建築的定向（朝向）讓自然光能照進來。"],
    ["mandatory", "強制的 / 必須的", "Wearing a seatbelt is mandatory by law.|Attendance at the safety training is mandatory.", "法律強制規定必須繫安全帶。|參加安全訓練是必須的。"],
    ["stationery supplies", "文具用品", "We need to order more stationery supplies for the office.|I bought pens and notebooks at the stationery supplies store.", "我們需要為辦公室訂購更多文具用品。|我在文具店買了筆和筆記本。"],
    ["fortified", "加強的 / 強化", "This cereal is fortified with extra vitamins.|They fortified the castle against the enemy.", "這種穀物強化了額外的維生素。|他們加強了城堡以抵禦敵人。"],
    ["magnified", "放大 / 擴大", "The microscope magnified the cells by 100 times.|His mistakes were magnified by the media.", "顯微鏡將細胞放大了 100 倍。|他的錯誤被媒體放大了。"],
    ["certified", "被證明的 / 公認的", "He is a certified personal trainer.|You need a certified copy of your passport.", "他是一名有證照的（被證明的）私人教練。|你需要一份你護照的公證（被證明的）影本。"],
    ["justified", "有正當理由的", "Her anger at the terrible service was completely justified.|I don't think the high price is justified.", "她對糟糕服務的憤怒是完全有正當理由的。|我不認為這個高價是合理的（有正當理由的）。"],
    ["formerly", "以前", "She was formerly a manager at Google.|The country was formerly known as Ceylon.", "她以前是 Google 的經理。|這個國家以前被稱為錫蘭。"],
    ["submit", "提交", "You must submit your application before Friday.|Please submit the report by the end of the day.", "你必須在週五前提交申請。|請在今天結束前提交報告。"],
    ["remarkably", "非常地 / 明顯地", "She played the piano remarkably well.|The two brothers look remarkably similar.", "她鋼琴彈得非常好（顯著地好）。|這對兄弟長得非常相似。"],
    ["rigid", "堅硬的 / 死板的", "He has a very rigid daily schedule.|The school's rules are too rigid for the students.", "他有著非常死板的每日行程。|這所學校的規定對學生來說太死板了。"],
    ["present", "目前的 / 出席的 / 禮物", "Everyone was present at the team meeting.|I bought a birthday present for my girlfriend.", "每個人都出席了團隊會議。|我為我女朋友買了一份生日禮物。"],
    ["humor", "幽默", "His dark sense of humor is not for everyone.|She handled the awkward situation with humor.", "他的黑色幽默不是每個人都懂。|她用幽默化解了尷尬的局面。"],
    ["assortment", "各式各樣", "The box contains an assortment of chocolates.|We offer a wide assortment of craft beers.", "這盒子裡裝了各式各樣的巧克力。|我們提供各式各樣的精釀啤酒。"],
    ["markers", "彩色筆 / 標記", "I bought a pack of colorful markers for drawing.|Place the markers on the map to show the route.", "我買了一包彩色筆來畫畫。|把標記放在地圖上以顯示路線。"],
    ["courteous", "有禮貌的", "The hotel staff was extremely friendly and courteous.|It is courteous to hold the door for others.", "飯店員工非常友善且有禮貌。|幫別人扶門是一種有禮貌的行為。"],
    ["prompt", "迅速的 / 立即的", "Thank you for your prompt reply.|He is always prompt in paying his bills.", "感謝您迅速的回覆。|他付帳單總是十分迅速。"],
    ["rate", "比率 / 費用 / 評價", "What is the current exchange rate for US dollars?|The hotel room rate is $150 per night.", "目前美元的匯率（比率）是多少？|飯店房價（費用）是每晚 150 美元。"],
    ["contributing", "貢獻 / 促成", "She is a contributing writer for the magazine.|Poor diet is a contributing factor to the disease.", "她是這本雜誌的特約（貢獻）撰稿人。|不良飲食是促成這種疾病的因素。"],
    ["specified", "指定的 / 明確說明的", "Please transfer the money to the specified account.|The task must be done in the specified manner.", "請將款項匯入指定的帳戶。|這項任務必須以指定的方式完成。"],
    ["amount", "數量 / 金額", "A huge amount of money was spent on the trip.|Please transfer the exact amount to this account.", "這趟旅行花費了龐大數量的金錢。|請將確切金額轉帳至此帳戶。"],
    ["assignment", "任務 / 作業", "The teacher gave us a difficult writing assignment.|He is on a special assignment in London.", "老師給了我們一項困難的寫作作業。|他正在倫敦執行一項特殊任務。"],
    ["wage", "工資", "The minimum wage has been increased this year.|Many workers are demanding a higher living wage.", "今年的基本工資調漲了。|許多工人要求提高能維持生活的工資。"],
    ["profit", "利潤", "The company made a huge profit last quarter.|He sold his used car at a profit.", "這家公司上個季度獲得了巨大的利潤。|他賣掉二手車賺取了利潤。"],
    ["supervisory experience", "管理經驗", "The job requires at least three years of supervisory experience.|She lacks supervisory experience for the manager role.", "這份工作需要至少三年的管理經驗。|她缺乏擔任經理職務的管理經驗。"],
    ["achieved", "達成 / 實現", "He finally achieved his dream of traveling the world.|Our team achieved all the sales targets.", "他終於達成了環遊世界的夢想。|我們的團隊達成了所有的銷售目標。"],
    ["formulas", "配方 / 公式", "You need to memorize these math formulas for the exam.|The company keeps its product formulas a secret.", "你需要為了考試背下這些數學公式。|公司對其產品配方保密。"],
    ["associate", "聯想 / 同事", "I always associate rainy days with sleeping in.|She is a senior associate at the law firm.", "我總是把下雨天和睡懶覺聯想在一起。|她是這家律師事務所的資深合夥人（同事）。"],
    ["finance", "財務 / 金融", "He works in the finance department of a bank.|She is studying finance at the university.", "他在一家銀行的財務部門工作。|她正在大學主修金融。"],
    ["after all", "畢竟", "Don't be too hard on him; he is just a beginner after all.|We decided to go to the party after all.", "別對他太苛刻；他畢竟只是個初學者。|我們畢竟（最終還是）決定去參加派對了。"],
    ["as long as", "只要", "You can stay here as long as you want.|I will go with you, as long as you drive.", "你想待多久就可以待多久（只要你喜歡）。|我會跟你去，只要你開車。"],
    ["emphasis", "強調 / 重點", "The school places a strong emphasis on physical education.|In this word, the emphasis is on the first syllable.", "這所學校非常強調體育。|在這個單字中，重音（強調）在第一個音節。"],
    ["cuisines", "美食 / 料理", "New York offers a variety of international cuisines.|Thai and Italian are my favorite cuisines.", "紐約提供各種國際美食。|泰國菜和義大利菜是我最喜歡的料理。"],
    ["recycling", "回收", "Please put the plastic bottles in the recycling bin.|Our city has a strict recycling policy.", "請把寶特瓶放進回收桶裡。|我們城市有嚴格的回收政策。"],
    ["conveyor belt", "輸送帶", "We waited for our luggage at the conveyor belt in the airport.|The parts move along the conveyor belt in the factory.", "我們在機場的輸送帶旁等行李。|零件在工廠的輸送帶上移動。"],
    ["discarded", "廢棄的 / 丟棄的", "The beach was littered with discarded plastic bags.|Please put discarded paper in this box.", "海灘上散落著被丟棄的塑膠袋。|請將廢棄的紙張放入這個箱子。"],
    ["landfill", "垃圾掩埋場", "Most of our city's waste goes to the landfill.|They are planning to build a park over the old landfill.", "我們城市大部分的垃圾都送往垃圾掩埋場。|他們正計畫在舊垃圾掩埋場上建一座公園。"],
    ["disposal", "處理 / 清除", "Proper waste disposal is important for the environment.|I am at your disposal if you need any help.", "適當的廢棄物處理對環境很重要。|如果你需要任何幫助，我任憑你差遣（由你處置）。"],
    ["discs", "光碟 / 圓盤", "He has a huge collection of old movie discs.|The doctor said he has a slipped disc in his back.", "他收藏了大量的老電影光碟。|醫生說他的背部有椎間盤（圓盤）突出。"],
    ["cardboard", "厚紙板", "We packed our books into a cardboard box.|The sign was made from a piece of folded cardboard.", "我們把書裝進厚紙板箱裡。|這個招牌是用一塊摺疊的厚紙板做的。"],
    ["flattened", "壓扁的 / 變平的", "Make sure the boxes are flattened before recycling.|The strong wind flattened the crops.", "回收前請確保箱子被壓扁了。|強風把農作物吹平了。"],
    ["barrier", "障礙物 / 柵欄", "The language barrier made communication difficult.|Police set up a metal barrier to control the crowd.", "語言障礙讓溝通變得很困難。|警察設置了金屬柵欄來控制人群。"],
    ["shredded", "切絲的 / 撕碎的", "I like to add shredded cheese to my salad.|He threw the shredded documents into the trash.", "我喜歡在沙拉裡加起司絲（切絲的起司）。|他把撕碎的文件扔進了垃圾桶。"],
    ["magnet", "磁鐵", "I bought a fridge magnet as a souvenir.|His charming personality makes him a magnet for friends.", "我買了一個冰箱磁鐵當紀念品。|他迷人的個性讓他像一塊磁鐵般吸引朋友。"],
    ["sort", "排序 / 分類", "Please sort these files by date.|What sort of music do you like listening to?", "請依日期將這些檔案排序（分類）。|你喜歡聽哪種類型的音樂？"],
    ["crush", "壓碎", "Be careful not to crush the fragile items in the bag.|The machine is used to crush large rocks.", "小心不要壓碎袋子裡的易碎物品。|這台機器是用來壓碎大石頭的。"],
    ["shatter", "粉碎 / 砸碎", "The baseball hit the window and made it shatter.|His dream to play in the major league was shattered.", "棒球擊中窗戶並使其粉碎。|他在大聯盟打球的夢想破滅了。"],
    ["optical scanner", "光學掃描機", "The cashier used an optical scanner to read the barcode.|The test is graded by an optical scanner.", "收銀員用光學掃描機讀取條碼。|這份考卷由光學掃描機評分。"],
    ["raw materials", "原料", "The factory needs a steady supply of raw materials.|The cost of raw materials has increased this year.", "這家工廠需要穩定的原料供應。|今年原料的成本增加了。"],
    ["fill", "裝滿 / 填寫", "Please fill the glass with water.|Don't forget to fill out the application form.", "請把玻璃杯裝滿水。|別忘了填寫申請表。"],
    ["diverse", "多樣的", "New York is a culturally diverse city.|Our team has a diverse range of skills.", "紐約是一個文化多樣的城市。|我們的團隊擁有多樣化的技能。"],
    ["broader", "更寬廣的", "Traveling gives you a broader perspective on life.|We need to look at the broader picture.", "旅行能給你更寬廣的人生視角。|我們需要著眼於更宏觀（寬廣）的局面。"],
    ["enthusiasm", "熱情", "He showed a lot of enthusiasm for the new project.|She tackled the problem with great enthusiasm.", "他對這個新專案展現了高度的熱情。|她以極大的熱情解決了這個問題。"],
    ["aspects", "方面 / 外觀", "We need to consider all aspects of the plan.|The financial aspects of the deal are very complex.", "我們需要考慮這個計畫的所有方面。|這筆交易的財務方面非常複雜。"],
    ["promise", "承諾", "I promise I will call you when I arrive in the US.|Don't make a promise you can't keep.", "我承諾我抵達美國時會打給你。|不要許下你無法遵守的承諾。"],
    ["spread", "散佈 / 塗抹", "The news spread quickly across the internet.|I like to spread butter on my toast.", "這個消息在網路上迅速散佈開來。|我喜歡在吐司上塗抹奶油。"],
    ["enterprise", "企業 / 事業心", "He works for a large multinational enterprise.|Starting a new business is a risky enterprise.", "他在一家大型跨國企業工作。|創業是一項充滿風險的事業。"],
    ["frustrated", "感到沮喪的", "I am so frustrated with this slow internet.|She felt frustrated when she couldn't solve the puzzle.", "我對這緩慢的網路感到非常沮喪（受挫）。|當她無法解開謎題時，她感到很挫折。"],
    ["approach", "接近 / 方法", "The train will soon approach the station.|We need a new approach to solve this issue.", "火車即將接近車站。|我們需要一個新方法來解決這個問題。"],
    ["consider", "考慮", "Please consider my offer carefully.|We didn't consider the traffic when planning the trip.", "請仔細考慮我的提議。|我們在規劃行程時沒有把交通狀況考慮進去。"]
];
